### ISSUE TITLE
Use a Result type instead of so many unwraps + contributor wishlist/todolist?

### ISSUE THREAD

**Issue by tonyb983** [lazops/rustea#4]
I know this is a pretty new library, but you may want to consider implementing a library-wide `Result`/`Error` type for unexpected circumstances instead of using so many `unwrap` calls. Even the demo from the readme closes with a panic when Ctrl+C is pressed instead of quitting gracefully. 

Also, I'd be happy to help with this or anything that is within the realm of my meager rust skill set. Maybe you could put together a "todo-list" or "wish-list" of sorts, for anything that you would be open to contribution on?

**Comment by lazops** [comment]
I 100% agree this is something I would like to implement. I am considering using [thiserror](https://github.com/dtolnay/thiserror) to act as an error type. As for the wish-list, I am essentially just opening up issues myself with features I can think of. If you don't see me assigning myself to one, feel free to take it on! If you think some type of `TODO.md` would be helpful, let me know and I will create one.

BTW, do you mind giving me some more information about the crash you are getting? I can close it with ctrl-c fine on my machine.

**Comment by tonyb983** [comment]
Sure, the terminal output is a generic thread panic pointing to your lib.rs:120:33.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', C:\Users\tonyb\.cargo\registry\src\github.com-1ecc6299db9ec823\rustea-0.1.1\src\lib.rs:120:33
```

Looks like it is stemming from the unwrap call in the second line of this segment of code from the `run` function:
```rust
thread::spawn(move || loop {
        let cmd = cmd_rx.recv().unwrap();

        let msg_tx2 = msg_tx2.clone();
        thread::spawn(move || {
            if let Some(msg) = cmd() {
                msg_tx2.send(msg).unwrap();
            }
        });
    });

**Comment by lazops** [comment]
Okay, I think I've determined the issue comes from improperly terminating the threads. I've just updated with a hot patch that returns instead of breaking out of the loop, but I will be patching it up to signal the threads to shut down after work today 👍 thanks for pointing out this error!

**Comment by tonyb983** [comment]
If you have some time and are open to it, I'd love to chat and see where and how I can help. I currently happen to have an abundance of free time and I'm looking for rust repositories I can help contribute to. If you're on discord, my username is `sugarpil1#2379`, send me a message any time. 

Let me know when you've read this as I'll probably delete this message (or at least my discord name) at some point.

**Comment by lazops** [comment]
Right now, I put up a "patch" that breaks the thread loop on the command receiver if it errors. This may be a permanent solution because there is no other times when the command receiver should panic. I've given it some more thought, and I'm not quite sure how I want to handle custom result types. In my opinion, `io::Result` is an appropriate response type for this as in the end all of the real points of failure come from `io` operations that are being processed by crossterm.

The only other point of failure in the library comes from the channels. Aside from the exit issue (I think this happens because the channel is trying to be closed down, but a receive was happening which should be fixed now), I think leaving the channels to unwrap _could_ be okay. My main reasoning for this is that they should not, at any point, fail. If the channels fail that is an appropriate cause for panic, and scenarios in which they would fail are generally irrecoverably. Using a standard library error type has huge advantages that outweigh the rare chance of a message failing, in my opinion. What are your thoughts?

**Comment by lazops** [comment]
Closing this issue for now. If a custom result type becomes necessary, I will open this again.
